const tripArray = [
    {
      travelName: 'Business Meeting with Nirvana Association',
      from: 'New York',
      to: 'Los Angeles',
      departureDate: '20-Sep-2023',
      returnDate: '22-Sep-2023',
      status: 'cancelled',
      tripStatus: 'upcoming',
    },
    {
      travelName: 'Vacation',
      from: 'London',
      to: 'Paris',
      departureDate: '10-Jul-2023',
      returnDate: '18-Jul-2023',
      status: 'approved',
      tripStatus: 'upcoming',
    },
    {
      travelName: 'Conference',
      from: 'San Francisco',
      to: 'Chicago',
      departureDate: '05-Oct-2023',
      returnDate: '07-Oct-2023',
      status: 'upcoming',
      tripStatus: 'upcoming',
    },
    {
      travelName: 'Family Reunion',
      from: 'Miami',
      to: 'Orlando',
      departureDate: '12-Aug-2023',
      returnDate: '15-Aug-2023',
      status: 'approved',
      tripStatus: 'inTransit',
    },
    {
      travelName: 'Adventure Trip',
      from: 'Sydney',
      to: 'Auckland',
      departureDate: '25-Nov-2023',
      returnDate: '30-Nov-2023',
      status: 'cancelled',
      tripStatus: 'not',
    },
    {
      travelName: 'Client Visit',
      from: 'Chicago',
      to: 'Dallas',
      departureDate: '02-Dec-2023',
      returnDate: '04-Dec-2023',
      status: 'approved',
      tripStatus: '',
    },
    {
      travelName: 'Honeymoon',
      from: 'Venice',
      to: 'Santorini',
      departureDate: '08-Jun-2023',
      returnDate: '15-Jun-2023',
      status: 'rejected',
      tripStatus: 'completed',
    },
    {
      travelName: 'Family Vacation',
      from: 'Orlando',
      to: 'Miami',
      departureDate: '03-Jul-2023',
      returnDate: '08-Jul-2023',
      status: 'approved',
      tripStatus: 'pending',
    },
    {
      travelName: 'Training Seminar',
      from: 'Houston',
      to: 'Atlanta',
      departureDate: '17-Sep-2023',
      returnDate: '19-Sep-2023',
      status: 'pending',
      tripStatus: 'cancelled',
    },
    {
      travelName: 'Ski Trip',
      from: 'Denver',
      to: 'Aspen',
      departureDate: '12-Jan-2023',
      returnDate: '15-Jan-2023',
      status: 'approved',
      tripStatus: 'not',
    },
  ];

  export {tripArray}